### ISSUE TITLE
Add option to recalculate collision surface normals

### ISSUE THREAD

**Issue by ThatNintendoNerd** [ultimate-research/lvd-rs#5]
An option like this would significantly speed up `.lvd` file creation or the adjustment of it. When the option is unspecified in the console command, the application should not recalculate. Only should it when requested by the user.

Additionally, the option to recalculate specific collision groups may prove to be useful when the user wishes to retain the data of vanilla collision groups unless the application is able to recalculate collision surface normals and retain the existing value.

**Comment by ScanMountGoat** [comment]
> An option like this would significantly speed up `.lvd` file creation or the adjustment of it. When the option is unspecified in the console command, the application should not recalculate. Only should it when requested by the user.

This could be handled by adding a `calculate_normals(&mut self)` method to `Collision`.

> Additionally, the option to recalculate specific collision groups may prove to be useful when the user wishes to retain the data of vanilla collision groups unless the application is able to recalculate collision surface normals and retain the existing value.

It's highly unlikely to be able to calculate identical values even given the same points due to floating point rounding errors. Only updating certain groups would be tricky to do just with the CLI arguments. This would be relatively straightforward from Rust code since you can just call the method on some of the collisions.

**Comment by ThatNintendoNerd** [comment]
It would probably be better to have this feature in an up-to-date user-friendly LVD editor application or a higher-level library. Closing for now as it's not within the current scope of the project.
